pub mod clone;
pub mod edit_mcp_config;
pub mod edit_skills_config;
pub mod explain_skill;
pub mod learn;
pub mod link;
pub mod link_skills;
pub mod list_skills;
pub mod prepare;
pub mod pull;
pub mod register_mcp;
pub mod remove_mcp;
pub mod setup;
pub mod update_gitignore;

pub use learn::{LearnAction, LearnError};
pub use link::{Link, SCHOOL_FOLDERS};
pub use prepare::{Prepare, PrepareError, PrepareResult};
pub use pull::{ChangeKind, Pull, PullOutcome, SkillChange};
pub use register_mcp::{register_missing as register_missing_mcp, RegisterMcp, RegisterMcpError};
pub use remove_mcp::RemoveMcp;
pub use setup::{Setup, SetupError};
pub use update_gitignore::UpdateGitignore;
