#!/bin/sh
#
# Provision real backend CLIs from source into a disposable, repo-local pen.
#
#   ./scripts/harnesses.sh            # status of every known backend
#   ./scripts/harnesses.sh hermes     # clone-or-pull, build, wrap as .harnesses/bin/hermes
#   ./scripts/harnesses.sh clean      # remove the pen
#
# The pen is gitignored and never on `cargo test`'s path. See
# docs/guides/harnesses.md.

set -e

root=$(cd "$(dirname "$0")/.." && pwd)
pen="$root/.harnesses"
bin="$pen/bin"

# name | git url | build command | binary path inside the clone | vars to pin at the
# backend's state dir, on top of the XDG vars every wrapper pins
backends() {
  cat <<'TABLE'
codex|https://github.com/openai/codex|cargo build --release --manifest-path codex-rs/Cargo.toml|codex-rs/target/release/codex|CODEX_HOME
opencode|https://github.com/sst/opencode|bun install|packages/opencode/bin/opencode|OPENCODE_CONFIG_DIR
TABLE
}

lookup() {
  backends | grep "^$1|" || true
}

status() {
  backends | while IFS='|' read -r name url _ _ _; do
    if [ -x "$bin/$name" ]; then
      echo "$name	built	$bin/$name"
    elif [ -d "$pen/$name" ]; then
      echo "$name	cloned	$pen/$name"
    else
      echo "$name	absent	$url"
    fi
  done
}

provision() {
  entry=$(lookup "$1")
  if [ -z "$entry" ]; then
    echo "unknown backend: $1" >&2
    echo "known: $(backends | cut -d'|' -f1 | tr '\n' ' ')" >&2
    exit 2
  fi

  IFS='|' read -r name url build binpath vars <<ENTRY
$entry
ENTRY

  clone="$pen/$name"

  if [ -d "$clone/.git" ]; then
    echo "==> pulling $name"
    git -C "$clone" pull --ff-only
  else
    echo "==> cloning $name from $url"
    mkdir -p "$pen"
    git clone --depth 1 "$url" "$clone"
  fi

  echo "==> building $name: $build"
  (cd "$clone" && nice -n 19 sh -c "$build")

  if [ ! -x "$clone/$binpath" ]; then
    echo "build finished but $clone/$binpath is not executable" >&2
    exit 1
  fi

  mkdir -p "$bin"
  wrapper="$bin/$name"

  # Unlink first: `>` follows a symlink and writes through to its target, and an
  # earlier version of this script left symlinks here pointing into the venv.
  rm -f "$wrapper"

  # A wrapper, not a symlink: whatever the backend writes should land in the pen
  # without the caller having to remember an env var. State goes in the clone —
  # a backend given an empty state dir tries to install itself into it, and the
  # clone is already a populated install. Soft containment: a backend that
  # ignores these vars still reaches the host.
  {
    echo "#!/bin/sh"
    echo "# Generated by scripts/harnesses.sh — edit the table there, not here."
    echo "state=\"$clone\""
    for var in XDG_CONFIG_HOME XDG_DATA_HOME XDG_CACHE_HOME XDG_STATE_HOME $vars; do
      echo "export $var=\"\$state\""
    done
    echo "exec \"$clone/$binpath\" \"\$@\""
  } > "$wrapper"
  chmod +x "$wrapper"

  echo "==> $wrapper"
}

case "$1" in
  "")
    status
    ;;
  clean)
    if [ -d "$pen" ]; then
      rm -rf "$pen"
      echo "removed $pen"
    else
      echo "nothing to clean"
    fi
    ;;
  *)
    provision "$1"
    ;;
esac
