#!/bin/sh
# Regenerate src/skills/name/ucd_tables.rs — the Unicode general-category
# whitelist backing skill-name admission (model.md § Name Admission).
#
# Decision: committed table, zero build/runtime deps (admission-plan resolution 6).
# This is a ONE-SHOT generator run by a human on Unicode-version bumps, NOT a
# build step. Do not move into build.rs — that reintroduces a build dep.
#
# The whitelist is fail closed: staleness only ever rejects newly-assigned
# codepoints (safe direction), never admits new ones. Bump UCD_VERSION on demand.
#
# Requires: ucd-generate (cargo install ucd-generate), curl, unzip, perl.

set -eu

UCD_VERSION="17.0.0"
UCD_URL="https://www.unicode.org/Public/${UCD_VERSION}/ucd/UCD.zip"

# Whitelist: L* M* N* P* S* Zs. Everything in C* (control/format/unassigned/
# private-use) and Zl/Zp (line/paragraph separators) is rejected by omission.
# Keep this list in sync with model.md § Approach.
CLASSES="Lu,Ll,Lt,Lm,Lo,Mn,Mc,Me,Nd,Nl,No,Pc,Pd,Ps,Pe,Pi,Pf,Po,Sm,Sc,Sk,So,Zs"

REPO_ROOT=$(CDPATH= cd "$(dirname "$0")/.." && pwd)
OUT="$REPO_ROOT/src/skills/name/ucd_tables.rs"
UCD_DIR="$REPO_ROOT/target/ucd/$UCD_VERSION"

if ! command -v ucd-generate >/dev/null 2>&1; then
    echo "ucd-generate not found; install with: cargo install ucd-generate" >&2
    exit 1
fi

# Fetch and unpack the UCD flat files ucd-generate reads from. Version-scoped
# so a version bump fetches fresh data instead of reusing a stale cache.
if [ ! -f "$UCD_DIR/UnicodeData.txt" ]; then
    mkdir -p "$UCD_DIR"
    echo "Fetching UCD ${UCD_VERSION} ..."
    curl -fsSL "$UCD_URL" -o "$UCD_DIR/UCD.zip"
    unzip -oq "$UCD_DIR/UCD.zip" -d "$UCD_DIR"
fi

echo "Generating $OUT ..."
ucd-generate general-category --combined \
    --include "$CLASSES" \
    --name ALLOWED_NAME_CHARS \
    "$UCD_DIR" >"$OUT"

# Post-process the generator's own output (idempotent — runs on fresh emit each
# time):
#   1. Point the "DO NOT EDIT" banner at this script.
#   2. Strip the absolute repo-root prefix the generator records in its banner,
#      so the committed file stays machine-independent.
#   3. Drop the `&'static` lifetime so the table is a plain const slice.
perl -0pi -e "s/IT WAS AUTOMATICALLY GENERATED BY:/Regenerate it with scripts\/regen-ucd.sh, which runs:/" "$OUT"
perl -0pi -e "s{\\Q$REPO_ROOT/\\E}{}g" "$OUT"
perl -0pi -e "s/&'static \\[/&[/" "$OUT"

echo "Done. Review the diff and rebuild."
